services:
 db:
   image: postgres
   restart: always
   environment:
     POSTGRES_USERNAME: postgres
     POSTGRES_PASSWORD: example
   ports:
     - 5432:5432
   volumes:
     - postgres-data:/var/lib/postgresql/data
 app:
   build:
     context: .
   ports:
     - 5165:80
   depends_on:
     - db
volumes:
 postgres-data: